#!/bin/bash

# install vim plugins
echo "Updating vim plugins"
if command -v nvim >/dev/null 2>&1; then
    echo "Neovim is installed. Updating plugins..."
    nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
else
    echo "Neovim is not installed. Skipping..."
fi

echo

# update bat cache
echo "Updating bat cache"
if command -v bat > /dev/null 2>&1; then
    echo "Bat is installed. Updating cache..."
    bat cache --build
else
    echo "Bat is not installed. Skipping"
fi

echo

# create hblock configuration in /etc
echo "Configuring hblock"

HBLOCK_CONFIG_DIR=/etc/hblock.d

if [ -d $HBLOCK_CONFIG_DIR ]; then
    echo "Found old hblock configuration directory, removing..."
    if [ -L $HBLOCK_CONFIG_DIR ]; then
	sudo rm $HBLOCK_CONFIG_DIR
    else
	sudo rm -rf $HBLOCK_CONFIG_DIR
    fi
fi

echo "Creating hblock configuration"
sudo cp -r ~/.config/hblock.d $HBLOCK_CONFIG_DIR

if command -v hblock >/dev/null 2>&1; then
    echo "Hblock is installed. Updating host file..."
    hblock
else
    echo "Hblock is not installed. Skipping..."
fi
