#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  mouse_follows_focus on \
  focus_follows_mouse autofocus \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.1 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.9 \
  window_opacity on \
  insert_feedback_color 0xffe67e80 \
  split_ratio 0.5 \
  split_type auto \
  auto_balance on \
  top_padding 16 \
  bottom_padding 16 \
  left_padding 16 \
  right_padding 16 \
  window_gap 16 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="System Information" app="^System Information$" title=".*" manage=off

# workspaces
spaces=$(yabai -m query --spaces | jq 'length')
desired_spaces=$((10 - spaces))
i=0
while [ $i -lt $desired_spaces ]; do
  yabai -m space --create
  i=$((i + 1))
done

# sketchybar
sketchybar

echo "yabai configuration loaded.."
