#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
  height=16
  position=bottom
  color=0x00000000
)
default=(
  icon.font="VictorMono Nerd Font:SemiBold:13.0"
  label.font="VictorMono Nerd Font:SemiBold:13.0"
)
front_app=(
  script="$PLUGIN_DIR/front_app.sh"
  icon.drawing=off
  label.color=0xffdbbc7f
)
aerospace=(
  label.drawing=off
  icon.color=0x88dbbc7f
  icon.highlight_color=0xffdbbc7f
  icon.padding_left=6
  icon.padding_right=6
)
clock=(
  script="$PLUGIN_DIR/clock.sh"
  icon.drawing=off
  label.color=0xffdbbc7f
)

sketchybar --add event aerospace_workspace_change

sketchybar --default "${default[@]}"

sketchybar --bar "${bar[@]}"

sketchybar --add item clock left --set clock "${clock[@]}"

sketchybar --add item front_app center --set front_app "${front_app[@]}" --subscribe front_app front_app_switched

for sid in $(aerospace list-workspaces --all | tail -r); do
  sketchybar --add item "space.$sid" right \
    --set "space.$sid" icon="$sid" click_script="aerospace workspace $sid" script="$PLUGIN_DIR/aerospace.sh $sid" "${aerospace[@]}" \
    --subscribe "space.$sid" aerospace_workspace_change
done

sketchybar --update
